sudo: false

cache:
    directories:
        - $HOME/env

language: python

notifications:
    email: false

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"

env:
    - FFMPEG_VERSION=4.2
    - FFMPEG_VERSION=4.1
    - FFMPEG_VERSION=4.0.2
    - FFMPEG_VERSION=3.4
    - FFMPEG_VERSION=3.2.4

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    # install your own package into the environment
    - pip install -e .[tests]

script:
    - python --version
    - py.test tests

after_success:
    - pip uninstall -y stempeg

after_failure:
    - pip uninstall -y stempeg
